version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: stock-analysis-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: stock-analysis
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - stock-analysis-network

volumes:
  mongodb_data:

networks:
  stock-analysis-network:
    driver: bridge
